In [1]:
1 + 2

3

### 

In [2]:
(1 + 2 * 3- 4) /5

0.6

In [3]:
2**8 

256

In [4]:
x = 1

In [5]:
y = 1/ 3

In [6]:
x + y

1.3333333333333333

In [7]:
data_1 = 1/5

In [8]:
data_2 = 3 / 5

In [9]:
data_1 + data_2 

0.8

###2.3 型

In [10]:
type(100)

int

In [11]:
type(100.1)

float

In [12]:
x = 100

In [13]:
type(x)

int

In [14]:
x = 100.1

In [15]:
type(x)

float

In [16]:
x = 'learning'

In [17]:
type(x)

str

###2.4 print文

In [18]:
x = 1 / 3
x 
y = 2 / 3
y

0.6666666666666666

In [19]:
x = 1 / 3
print(x) 
y = 2 / 3
print(y)

0.3333333333333333
0.6666666666666666


In [20]:
print('x = ' + str(x))

x = 0.3333333333333333


In [21]:
print('weight = {0} kg'.format(x))

weight = 0.3333333333333333 kg


In [22]:
x = 1 / 3
y = 1 / 7
z = 1 / 4

print('weight: {0} kg,{1} kg, {2}kg'.format(x,y,z))

weight: 0.3333333333333333 kg,0.14285714285714285 kg, 0.25kg


In [24]:
print('weight: {0: .2f} kg , y = {1: .2f} kg ,z = {2: .2f} kg'.format(x,y,z))

weight:  0.33 kg , y =  0.14 kg ,z =  0.25 kg


###### 2.8 list

In [27]:
num = [2,4,6,8,10]
for i , n in enumerate(num):
    num[i] = n * 2
print(num)

[4, 8, 12, 16, 20]


### 2.9 ベクトル

In [28]:
import numpy as np

In [32]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [33]:
print(x)

[1 2 3]


In [35]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [36]:
print(x + y)

[5 7 9]


In [37]:
type(x)

numpy.ndarray

In [38]:
x[0]

1

In [40]:
x[0] = 100
print(x)

[100   2   3]


In [41]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [42]:
print(np.arange(5,10))

[5 6 7 8 9]


In [45]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [46]:
x.shape

(2, 3)

In [47]:
w,h = x.shape
print(w)
print(h)

2
3


In [48]:
x[1,2]

6

In [49]:
    print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [50]:
print(np.ones((10,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [51]:
np.random.rand(2,3)

array([[0.65394777, 0.41332774, 0.61351303],
       [0.18214464, 0.14133991, 0.2246242 ]])

In [53]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [55]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [58]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
x = np.array([[4,4,4],[8,8,8]])
y = np.array([[1,1,1],[2,2,2]])
print(x + y)

[[ 5  5  5]
 [10 10 10]]


In [60]:
print(10 * x)

[[40 40 40]
 [80 80 80]]


In [61]:
print(np.exp(x))

[[  54.59815003   54.59815003   54.59815003]
 [2980.95798704 2980.95798704 2980.95798704]]


In [62]:
v= np.array([[1,2,3],[4,5,6]])
w = np.array([[1,1],[2,2],[3,3]])
            

In [63]:
print(v.dot(w))

[[14 14]
 [32 32]]
