In [1]:
import numpy as np
a = np.array([2,1])

In [2]:
print(a)

[2 1]


In [3]:
type(a)

numpy.ndarray

In [6]:
c = np.array([[1,2],[3,4]])
print(c)

[[1 2]
 [3 4]]


In [8]:
d = np.array([[1],[2]])
print(d)

[[1]
 [2]]


In [10]:
print(d.T)

[[1 2]]


In [12]:
a = np.array([2,1])
b = np.array([1,3])
print(a + b)
print(a - b)

[3 4]
[ 1 -2]


In [14]:
print(2*a)
print(a.dot(b))

[4 2]
5


In [15]:
print(np.linalg.norm(a))

2.23606797749979


In [17]:
c = np.array([3,4])
print(np.linalg.norm(c))

5.0


## 4.2.2 内積

In [18]:
import numpy as np
a = np.ones(1000)
b = np.arange(1,1001)
print(a.dot(b))

500500.0


## 行列


In [19]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
A = np.array([[1,2],[3,4]])
invA = np.linalg.inv(A)
print(invA)

[[-2.   1. ]
 [ 1.5 -0.5]]
